-- AlterTable
ALTER TABLE `bank` ADD COLUMN `tbo` INTEGER NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `datapembiayaan` ADD COLUMN `est_takeover` DATETIME(3) NULL,
    ADD COLUMN `pembiayaan_sebelumnya2` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `jenispembiayaan` ADD COLUMN `blokir` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('MASTER', 'ENTRY_DATA', 'BANK', 'VERIFIKASI', 'CHECKER', 'MAKER', 'APPROVAL', 'MARKETING', 'OPERASIONAL', 'BISNIS', 'PEMBERKASAN', 'KEUANGAN', 'MANAGEMENT', 'AUDIT', 'ADMINISTRASI') NOT NULL;
