-- CreateTable
CREATE TABLE `flagging` (
    `id` VARCHAR(191) NOT NULL,
    `status_peserta` VARCHAR(10) NOT NULL,
    `notas` VARCHAR(20) NOT NULL,
    `kantor_cabang` VARCHAR(20) NOT NULL,
    `alamat_cabang` VARCHAR(60) NOT NULL,
    `nipnrp` VARCHAR(20) NOT NULL,
    `nama_penerima` VARCHAR(40) NOT NULL,
    `jandadudaypdari` VARCHAR(40) NOT NULL,
    `alamatrumah` VARCHAR(80) NOT NULL,
    `penerbitskep` VARCHAR(10) NULL,
    `noskep` VARCHAR(40) NOT NULL,
    `jnsdapem` VARCHAR(10) NOT NULL,
    `jnspens` VARCHAR(40) NOT NULL,
    `ktrbaydapem` VARCHAR(60) NOT NULL,
    `norek` VARCHAR(20) NOT NULL,
    `stsdapem` VARCHAR(50) NOT NULL,
    `tgllahir_penerima` VARCHAR(10) NOT NULL,
    `tgllahir_jandadudayp` VARCHAR(10) NOT NULL,
    `nodosir` BIGINT NOT NULL,
    `tglskep` VARCHAR(10) NULL,
    `tmtpens` VARCHAR(10) NOT NULL,
    `nudapem` VARCHAR(10) NULL,
    `kdjiwa` SMALLINT NOT NULL,
    `pangkat` VARCHAR(50) NOT NULL,
    `tmt_stop` VARCHAR(10) NOT NULL,
    `kdknsdapem` VARCHAR(10) NULL,
    `kdjnspens` VARCHAR(10) NULL,
    `kdktrbyrdapem` VARCHAR(10) NULL,
    `blthrincian` VARCHAR(20) NOT NULL,
    `penpok` VARCHAR(50) NOT NULL DEFAULT '0',
    `tistri` VARCHAR(50) NULL,
    `tanak` VARCHAR(50) NULL,
    `tpp` VARCHAR(50) NULL,
    `tpmtp` VARCHAR(50) NULL,
    `tkd` VARCHAR(50) NULL,
    `tdahor` VARCHAR(50) NULL,
    `tberas` VARCHAR(50) NULL,
    `tpph21` VARCHAR(50) NULL,
    `tcacat` VARCHAR(50) NULL,
    `pembulatan` VARCHAR(50) NULL,
    `jmlkotor` VARCHAR(50) NULL,
    `potpph21` VARCHAR(50) NULL,
    `potaskes` VARCHAR(50) NULL,
    `potassos` VARCHAR(50) NULL,
    `potkasda` VARCHAR(50) NULL,
    `potkpkn` VARCHAR(50) NULL,
    `potalimentasi` VARCHAR(50) NULL,
    `potsewarumah` VARCHAR(50) NULL,
    `potgantirugi` VARCHAR(50) NULL,
    `jmlpotongan` VARCHAR(50) NULL,
    `jmltotal` VARCHAR(50) NOT NULL DEFAULT '0',
    `kpkn` VARCHAR(10) NOT NULL,
    `spn` VARCHAR(40) NULL,
    `tgl_surat` VARCHAR(10) NOT NULL,
    `tgl_sekarang` VARCHAR(10) NOT NULL,
    `keluarga` TEXT NOT NULL,
    `jenishutang` VARCHAR(40) NOT NULL,
    `jumlah_hutang` VARCHAR(50) NULL,
    `cicilan` VARCHAR(50) NULL,
    `awal_flagging` VARCHAR(10) NULL,
    `akhir_flagging` VARCHAR(10) NULL,
    `mitra_flagging` VARCHAR(60) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
