-- AlterTable
ALTER TABLE `datataspen` ADD COLUMN `akhir_sks` VARCHAR(191) NULL,
    ADD COLUMN `alamat_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `golongan` VARCHAR(191) NULL,
    ADD COLUMN `jenis_pensiun` VARCHAR(191) NULL,
    ADD COLUMN `kecamatan_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `kelurahan_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `kode_pos_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `kota_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `masa_ktp_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `nama_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `nik_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `nipnrp` VARCHAR(191) NULL,
    ADD COLUMN `nomor_sk_pensiun` VARCHAR(191) NULL,
    ADD COLUMN `pekerjaan_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `penerbit_sk` VARCHAR(191) NULL,
    ADD COLUMN `provinsi_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `rt_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `rw_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `tanggal_lahir` VARCHAR(191) NULL,
    ADD COLUMN `tanggal_lahir_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `tanggal_nikah` VARCHAR(191) NULL,
    ADD COLUMN `tanggal_sk_pensiun` DATETIME(3) NULL,
    ADD COLUMN `tanggal_wafat` VARCHAR(191) NULL,
    ADD COLUMN `tempat_lahir_pasangan` VARCHAR(191) NULL,
    ADD COLUMN `tmt_pensiun` VARCHAR(191) NULL;
