-- AlterTable
ALTER TABLE `datapembiayaan` ADD COLUMN `user_update` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `datapengajuan` ADD COLUMN `jenis_asuransi` VARCHAR(191) NOT NULL DEFAULT 'CIU';

-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('MASTER', 'ENTRY_DATA', 'BANK', 'VERIFIKASI', 'CHECKER', 'MAKER', 'APPROVAL', 'MARKETING', 'OPERASIONAL', 'BISNIS', 'PEMBERKASAN', 'KEUANGAN', 'MANAGEMENT', 'AUDIT') NOT NULL;
